/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#004532',
          50: '#e6f0ed',
          100: '#b3d4cb',
          200: '#80b8a9',
          300: '#4d9c87',
          400: '#26856e',
          500: '#004532',
          600: '#003d2c',
          700: '#003325',
          800: '#002a1f',
          900: '#001a14',
          container: '#e6f0ed',
          'container-dark': '#003325',
        },
        secondary: {
          DEFAULT: '#fe932c',
          50: '#fff8f0',
          100: '#ffe8cc',
          200: '#ffd699',
          300: '#ffc466',
          400: '#ffb533',
          500: '#fe932c',
          600: '#e68500',
          700: '#cc7700',
          800: '#b36900',
          900: '#904d00',
          container: '#fff3e0',
          'container-dark': '#5c3600',
        },
        surface: {
          DEFAULT: '#f8f9fa',
          dim: '#f1f3f5',
          bright: '#ffffff',
          'container-lowest': '#ffffff',
          'container-low': '#f8f9fa',
          'container': '#f1f3f5',
          'container-high': '#e5e7eb',
          'container-highest': '#d1d5db',
          'container-dark': '#111827',
          'container-high-dark': '#1f2937',
          'container-highest-dark': '#374151',
        },
        outline: {
          DEFAULT: '#c4c7cc',
          variant: '#e5e7eb',
          'variant-dark': '#374151',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
          'container-dark': '#8c1d18',
        },
        inverse: {
          surface: '#2f3033',
          'on-surface': '#f1f3f5',
          primary: '#7dddb5',
        },
        fixed: {
          dim: '#8a9a95',
          DEFAULT: '#8a9a95',
          'dim-dark': '#4a635c',
        },
      },
      fontFamily: {
        quran: ['UthmanicHafs1', 'serif'],
        indopak: ['PDMS_Saleem_QuranFont', 'serif'],
        display: ['Playfair Display', 'serif'],
        body: ['Inter', 'sans-serif'],
        arabic: ['Amiri', 'serif'],
      },
      fontSize: {
        'display-hero': ['2.5rem', { lineHeight: '3rem', fontWeight: '700' }],
        'headline-lg': ['2rem', { lineHeight: '2.5rem', fontWeight: '600' }],
        'headline-lg-mobile': ['1.75rem', { lineHeight: '2.25rem', fontWeight: '600' }],
        'arabic-quran-lg': ['2.25rem', { lineHeight: '4rem', fontWeight: '400' }],
        'arabic-quran-md': ['1.75rem', { lineHeight: '3.25rem', fontWeight: '400' }],
        'body-translation': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'meta-info': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'label-caps': ['0.75rem', { lineHeight: '1rem', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      spacing: {
        'container-margin': '1.25rem',
        'stack-gap-sm': '0.5rem',
        'stack-gap-md': '1rem',
        'stack-gap-lg': '2rem',
        'section-padding': '2.5rem',
        'ayah-spacing': '1.5rem',
      },
      borderRadius: {
        pill: '9999px',
        '2xl': '1.5rem',
      },
      boxShadow: {
        'elevation-2': '0px 4px 20px rgba(0,0,0,0.05)',
        'glass': '0 8px 32px rgba(0,0,0,0.08)',
      },
      backdropBlur: {
        glass: '12px',
      },
    },
  },
  plugins: [],
};
